### PR TITLE
add a cli argument to display the version

### LINKED ISSUE #147: add a `--version` switch to the CLI

### PR DESCRIPTION
**Pull request by tonyfast**
closes #147

### CODE REVIEW

**Comment by bollwyvl** [comment]
We might not even need a short flag for `--version`. 

Often `-v` is reserved for `--verbose`, and might be nice to reserve for future work. 

I would intend to use this downstream to catch packaging issues with a "black box" invocation like:

```
importnb --version | grep -iE "importnb {{ version.replace('.', '\.') }}$"
```

Related to the as-of-yet untriaged `[extras]` item from #146: since `pip` check doesn't care about extras (last i checked), perhaps `--version` (or `--versions`) could also print out all of the versions of the packages it _would_ use, if asked:

```
                importnb        2023.11.3

available optional dependencies:

    [doit]      doit            0.36.0
    [ipython]   IPython         8.17.2
    [toml]      tomli           2.0.1
    [yaml]      ruamel.yaml     0.18.5

missing optional dependencies:

    no missing optional dependencies:

```

With a "fail" condition like:

```
missing optional dependencies:

    [yaml]      To enable importnb.YAML:

                pip install importnb[yaml] 
```

**Comment by tonyfast** [comment]
i'll think about adding the extra dependency version in another PR i think.

**Comment by bollwyvl** [comment]
Pushed using the the built-in `action="version"`, and re-ran the linters...

**Comment by bollwyvl** [comment]
image

**Comment by tonyfast** [comment]
Hell yea! Thanks for adding ruff. Was afraid to open that box and see how bad the formatting might be.

**Comment by bollwyvl** [comment]
Welp it's definitely just the "safely"-fixable stuff... I'm sure it would
have some complaints if given full agency...

**Review by bollwyvl — APPROVED** [review]

**Pull request merged**
